### ISSUE TITLE
UI prototype / Customer side

### ISSUE THREAD

**Issue by IFB299group59** [IFB299group59/crcGroup59#10]

**Comment by Rorschach21** [comment]
![account](https://user-images.githubusercontent.com/42431798/45446143-b934e500-b6fe-11e8-9c1e-5dbba4b61532.png)
![Uploading get_start.png…]()
![Uploading home_page.png…]()
![Uploading search_1.png…]()
![Uploading search_2.png…]()
![Uploading sign_in.png…]()
![Uploading sign_up.png…]()

**Comment by Rorschach21** [comment]
UI design/ users

**Comment by Rorschach21** [comment]
![get_start](https://user-images.githubusercontent.com/42431798/45446285-13ce4100-b6ff-11e8-9937-ef4a0a078e53.png)
![home_page](https://user-images.githubusercontent.com/42431798/45446293-192b8b80-b6ff-11e8-82e6-a15f97e587a3.png)
![sign_in](https://user-images.githubusercontent.com/42431798/45446298-1d57a900-b6ff-11e8-8e87-ce0052e0fb82.png)
![sign_up](https://user-images.githubusercontent.com/42431798/45446301-1fba0300-b6ff-11e8-8284-03e88c97c280.png)
![account](https://user-images.githubusercontent.com/42431798/45446305-221c5d00-b6ff-11e8-8100-62cccae909f5.png)
![search_1](https://user-images.githubusercontent.com/42431798/45446309-25174d80-b6ff-11e8-820b-06d246428988.png)
![search_2](https://user-images.githubusercontent.com/42431798/45446321-2779a780-b6ff-11e8-80a9-529df17063d6.png)
