### ISSUE TITLE
Filter Transmission

### ISSUE THREAD

**Issue by IFB299group59** [IFB299group59/crcGroup59#35]

**Comment by LEO999999999** [comment]
from django.shortcuts import render

# Create your views here.
def search(request):
    car_Transmission = request.META['carTransmission']
    if request.method == 'POST':
        data = None
        search_form = SearchForm(request.POST)
        if search_form.is_valid():
            data_type = search_form.cleaned_data.get('data_type')
            if data_type == "Manual":
                data = Data.objects.all().filter(Q(data_type="Manual"))
            elif data_type == "Automatic":
                data = Data.objects.all().filter()
            elif data_type:
                data = Data.objects.all().filter(data_type=data_type)

    else:
        search_form = SearchForm()
        data = "first_request"

    return render(request, 'car/search.html', {'search_form': search_form, 'data': data, "car_ID": carID})
