### ISSUE TITLE
Modify Cars

### ISSUE THREAD

**Issue by IFB299group59** [IFB299group59/crcGroup59#39]

**Comment by LEO999999999** [comment]
from django.shortcuts import render

def authenticate(username, password, customerID):
    try:
        if NEWACCOUNT.objects.filter(CID=customerID).exists():
            querySet = NEWACCOUNT.objects.get(CID = customerID)
            if ((querySet.USERNAME != username) or (querySet.PASSWORD != password)):
                return False
        else:
            return False
    except ValueError as error:
        return False
    else:
        return True




def modify_cars(request):
    navBar = navBarFunc(request)

    if (request.user.is_authenticated()):

        if request.method == 'POST':
            form = EditProfileForm(request.POST, instance=request.user)

            if form.is_valid():
                form.save()
                return redirect('modify')

        else:
            form = EditProfileForm(instance=request.user)
            args = {'form': form, 'navBar': navBar}
            return render(request, 'modify_cars.html', args)
    else:
        navBar = navBarFunc(request)
        notification = 'You need to be logged in to view this page. Log in <a href="/login/">here</a>.'
        context_dict = {'navBar' : navBar, 'notification' : notification}
        return render(request, 'home.html', context=context_dict)



def delete_cars(request):

    navBar = navBarFunc(request)

    if (request.user.is_authenticated()):
        if request.method == 'POST':
            form = DeleteUserForm(request.POST)

            if form.is_valid():
                rem = User.objects.get(carID=form.cleaned_data['carID'])
                if rem is not None:
                    rem.delete()
                    return redirect ('../../search')
                else:
                    return redirect('delete_car.html')
        # If send button not pressed, continue to display a input delete form and nav bar
        else:
            form = DeleteCarForm()
            context = {'form': form, 'navBar' : navBar}
            return render(request, 'delete_Car.html', context)
    else:
        navBar = navBarFunc(request)
        notification = 'You need to be logged in to view this page. Log in <a href="/login/">here</a>.'
        context_dict = {'navBar' : navBar, 'notification' : notification}
        return render(request, 'notification.html', context=context_dict)
