### ISSUE TITLE
Report/ Available cars

### ISSUE THREAD

**Issue by IFB299group59** [IFB299group59/crcGroup59#40]

**Comment by LEO999999999** [comment]
from django.shortcuts import render

# Create your views here.
def search(request):
    available_cars = request.META['availableCars']
    if request.method == 'POST':
        data = None
        search_form = SearchForm(request.POST)
        if search_form.is_valid():
            data_type = search_form.cleaned_data.get('data_type')
            if data_type == "available":
                data = Data.objects.all().filter(Q(data_type="available"))
            

    else:
        search_form = SearchForm()
        data = "first_request"

    return render(request, 'car/search/available.html', {'search_form': search_form, 'data': data, "car_ID": carID})
