### ISSUE TITLE
Search for Clients using Name & DOB

### ISSUE THREAD

**Issue by IFB299group59** [IFB299group59/crcGroup59#47]

**Comment by LEO999999999** [comment]
from django.shortcuts import render
from .forms import  LoginForm
from random import randint
import hashlib
import datetime
from decimal import Decimal


def authenticate(username, password, customerID):
    try:
        if NEWACCOUNT.objects.filter(CID=customerID).exists():
            querySet = NEWACCOUNT.objects.get(CID = customerID)
            if ((querySet.USERNAME != username) or (querySet.PASSWORD != password)):
                return False
        else:
            return False
    except ValueError as error:
        return False
    else:
        return True



def searchCustomer(request):
    
    if request.method == 'POST': # If the form has been submitted
        form = LoginForm(request.POST or None)
        if form.is_valid():                                                     # Checking if the submitted form is valid
            data = form.cleaned_data
            name = data['USERNAME']
            rawPassword = data['PASSWORD']
            password = hashlib.md5(rawPassword.encode('utf-8')).hexdigest()
            customerID = data['CID']
            isValidUser = authenticate(username = name, password = password, CID = customerID)     # Checking if the login credentials are valid
            try:
                if isValidUser:
                    querySet = NEWACCOUNT.objects.get(CID = customerID)# Obtaining the account detaild matching the submitted customerID
                    context = {
                        "customerName": querySet.customerName,
                        "customerPhoneNumber": cPhoneNumber,
                        "customerAddress": cAddress,
                        "customerBirthday": cBirthday,

                    }
                    return render(request, 'CRC/view-customerDetails.html', context)
                else:
                    raise ValueError('Incorrect Login Details. Please enter correct entries.')
            except ValueError as error:
                    context = {
                        "form": form,
                        "error_message": error.args[0],
                    }
                    return render(request, 'CRC/view-customerDetails.html', context)
    context = {
        "form": form,
    }
    return render(request, 'CRC/view-customerDetails.html', context)
